dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - 'pypy3'
cache: pip
install:
  - pip install .[test]
script:
  - flake8 *.py
  - pytest -v
after_success:
  - pip install -q -r requirements-cov.txt
  - pytest -v --cov flake8_isort --cov-report term-missing
  - coveralls
